Resources:
  MessageStore60E7AFC8:
    Type: AWS::S3::Bucket
    UpdateReplacePolicy: Retain
    DeletionPolicy: Retain
    Metadata:
      aws:cdk:path: SlStack/MessageStore/Resource
  MessageStoreNotifications0C91F785:
    Type: Custom::S3BucketNotifications
    Properties:
      ServiceToken:
        Fn::GetAtt:
          - BucketNotificationsHandler050a0587b7544547bf325f094a3db8347ECC3691
          - Arn
      BucketName:
        Ref: MessageStore60E7AFC8
      NotificationConfiguration:
        LambdaFunctionConfigurations:
          - Events:
              - s3:ObjectCreated:*
            LambdaFunctionArn:
              Fn::GetAtt:
                - DownloadHandler09CC40DB
                - Arn
    DependsOn:
      - MessageStoreAllowBucketNotificationsToSlStackDownloadHandler93BB4D311EA0437E
    Metadata:
      aws:cdk:path: SlStack/MessageStore/Notifications/Resource
  MessageStoreAllowBucketNotificationsToSlStackDownloadHandler93BB4D311EA0437E:
    Type: AWS::Lambda::Permission
    Properties:
      Action: lambda:InvokeFunction
      FunctionName:
        Fn::GetAtt:
          - DownloadHandler09CC40DB
          - Arn
      Principal: s3.amazonaws.com
      SourceAccount:
        Ref: AWS::AccountId
      SourceArn:
        Fn::GetAtt:
          - MessageStore60E7AFC8
          - Arn
    Metadata:
      aws:cdk:path: SlStack/MessageStore/AllowBucketNotificationsToSlStackDownloadHandler93BB4D31
  VodPollerServiceRole369446BC:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Statement:
          - Action: sts:AssumeRole
            Effect: Allow
            Principal:
              Service: lambda.amazonaws.com
        Version: "2012-10-17"
      ManagedPolicyArns:
        - Fn::Join:
            - ""
            - - "arn:"
              - Ref: AWS::Partition
              - :iam::aws:policy/service-role/AWSLambdaBasicExecutionRole
    Metadata:
      aws:cdk:path: SlStack/VodPoller/ServiceRole/Resource
  VodPoller741EDAA0:
    Type: AWS::Lambda::Function
    Properties:
      Code:
        S3Bucket:
          Ref: AssetParameters9faf4a2e9e23d7c99f598a2cee9743b3e97e406bf342999af601f2990e907147S3Bucket1545CFDC
        S3Key:
          Fn::Join:
            - ""
            - - Fn::Select:
                  - 0
                  - Fn::Split:
                      - "||"
                      - Ref: AssetParameters9faf4a2e9e23d7c99f598a2cee9743b3e97e406bf342999af601f2990e907147S3VersionKey3025D34E
              - Fn::Select:
                  - 1
                  - Fn::Split:
                      - "||"
                      - Ref: AssetParameters9faf4a2e9e23d7c99f598a2cee9743b3e97e406bf342999af601f2990e907147S3VersionKey3025D34E
      Role:
        Fn::GetAtt:
          - VodPollerServiceRole369446BC
          - Arn
      Environment:
        Variables:
          BUCKET:
            Ref: MessageStore60E7AFC8
          TWITCH_CLIENT_ID: 2nakqoqdxka9v5oekyo6742bmnxt2o
      Handler: handler.main
      MemorySize: 128
      Runtime: nodejs14.x
      Timeout: 900
    DependsOn:
      - VodPollerServiceRole369446BC
    Metadata:
      aws:cdk:path: SlStack/VodPoller/Resource
      aws:asset:path: /Users/russell/pillar/sl/lambdas/poller
      aws:asset:property: Code
  DownloadHandlerServiceRole4B8FD2FF:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Statement:
          - Action: sts:AssumeRole
            Effect: Allow
            Principal:
              Service: lambda.amazonaws.com
        Version: "2012-10-17"
      ManagedPolicyArns:
        - Fn::Join:
            - ""
            - - "arn:"
              - Ref: AWS::Partition
              - :iam::aws:policy/service-role/AWSLambdaBasicExecutionRole
    Metadata:
      aws:cdk:path: SlStack/DownloadHandler/ServiceRole/Resource
  DownloadHandlerServiceRoleDefaultPolicy4A78C071:
    Type: AWS::IAM::Policy
    Properties:
      PolicyDocument:
        Statement:
          - Action:
              - s3:DeleteObject*
              - s3:PutObject
              - s3:Abort*
            Effect: Allow
            Resource:
              - Fn::GetAtt:
                  - MessageStore60E7AFC8
                  - Arn
              - Fn::Join:
                  - ""
                  - - Fn::GetAtt:
                        - MessageStore60E7AFC8
                        - Arn
                    - /*
        Version: "2012-10-17"
      PolicyName: DownloadHandlerServiceRoleDefaultPolicy4A78C071
      Roles:
        - Ref: DownloadHandlerServiceRole4B8FD2FF
    Metadata:
      aws:cdk:path: SlStack/DownloadHandler/ServiceRole/DefaultPolicy/Resource
  DownloadHandler09CC40DB:
    Type: AWS::Lambda::Function
    Properties:
      Code:
        S3Bucket:
          Ref: AssetParametersb9ba1297b6c0c5415a0c53d8a98dc2351065c3f1f718e770a02231dba8f50543S3Bucket9FC5CCE8
        S3Key:
          Fn::Join:
            - ""
            - - Fn::Select:
                  - 0
                  - Fn::Split:
                      - "||"
                      - Ref: AssetParametersb9ba1297b6c0c5415a0c53d8a98dc2351065c3f1f718e770a02231dba8f50543S3VersionKey453DD4C9
              - Fn::Select:
                  - 1
                  - Fn::Split:
                      - "||"
                      - Ref: AssetParametersb9ba1297b6c0c5415a0c53d8a98dc2351065c3f1f718e770a02231dba8f50543S3VersionKey453DD4C9
      Role:
        Fn::GetAtt:
          - DownloadHandlerServiceRole4B8FD2FF
          - Arn
      Environment:
        Variables:
          BUCKET:
            Ref: MessageStore60E7AFC8
      Handler: handler.main
      MemorySize: 128
      Runtime: nodejs14.x
      Timeout: 900
    DependsOn:
      - DownloadHandlerServiceRoleDefaultPolicy4A78C071
      - DownloadHandlerServiceRole4B8FD2FF
    Metadata:
      aws:cdk:path: SlStack/DownloadHandler/Resource
      aws:asset:path: /Users/russell/pillar/sl/lambdas/downloader
      aws:asset:property: Code
  DownloadHandlerAllowInvokeSlStackReadyForDownloads8DCF2BE93A9C74E7:
    Type: AWS::Lambda::Permission
    Properties:
      Action: lambda:InvokeFunction
      FunctionName:
        Fn::GetAtt:
          - DownloadHandler09CC40DB
          - Arn
      Principal: sns.amazonaws.com
      SourceArn:
        Ref: ReadyForDownloadsEEACEEFF
    Metadata:
      aws:cdk:path: SlStack/DownloadHandler/AllowInvoke:SlStackReadyForDownloads8DCF2BE9
  DownloadHandlerReadyForDownloadsE6380D4D:
    Type: AWS::SNS::Subscription
    Properties:
      Protocol: lambda
      TopicArn:
        Ref: ReadyForDownloadsEEACEEFF
      Endpoint:
        Fn::GetAtt:
          - DownloadHandler09CC40DB
          - Arn
    Metadata:
      aws:cdk:path: SlStack/DownloadHandler/ReadyForDownloads/Resource
  ReadyForDownloadsEEACEEFF:
    Type: AWS::SNS::Topic
    Metadata:
      aws:cdk:path: SlStack/ReadyForDownloads/Resource
  ClipFinderServiceRole28A544E9:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Statement:
          - Action: sts:AssumeRole
            Effect: Allow
            Principal:
              Service: lambda.amazonaws.com
        Version: "2012-10-17"
      ManagedPolicyArns:
        - Fn::Join:
            - ""
            - - "arn:"
              - Ref: AWS::Partition
              - :iam::aws:policy/service-role/AWSLambdaBasicExecutionRole
    Metadata:
      aws:cdk:path: SlStack/ClipFinder/ServiceRole/Resource
  ClipFinderServiceRoleDefaultPolicyAFBF3421:
    Type: AWS::IAM::Policy
    Properties:
      PolicyDocument:
        Statement:
          - Action:
              - s3:GetObject*
              - s3:GetBucket*
              - s3:List*
            Effect: Allow
            Resource:
              - Fn::GetAtt:
                  - MessageStore60E7AFC8
                  - Arn
              - Fn::Join:
                  - ""
                  - - Fn::GetAtt:
                        - MessageStore60E7AFC8
                        - Arn
                    - /*
        Version: "2012-10-17"
      PolicyName: ClipFinderServiceRoleDefaultPolicyAFBF3421
      Roles:
        - Ref: ClipFinderServiceRole28A544E9
    Metadata:
      aws:cdk:path: SlStack/ClipFinder/ServiceRole/DefaultPolicy/Resource
  ClipFinderA73374EE:
    Type: AWS::Lambda::Function
    Properties:
      Code:
        S3Bucket:
          Ref: AssetParametersc0f83392cea6f4d5da56e5a1290550b964ce9db33ac1f17f2e99cf5e0857bbbfS3Bucket9D0E886A
        S3Key:
          Fn::Join:
            - ""
            - - Fn::Select:
                  - 0
                  - Fn::Split:
                      - "||"
                      - Ref: AssetParametersc0f83392cea6f4d5da56e5a1290550b964ce9db33ac1f17f2e99cf5e0857bbbfS3VersionKey5BF526C6
              - Fn::Select:
                  - 1
                  - Fn::Split:
                      - "||"
                      - Ref: AssetParametersc0f83392cea6f4d5da56e5a1290550b964ce9db33ac1f17f2e99cf5e0857bbbfS3VersionKey5BF526C6
      Role:
        Fn::GetAtt:
          - ClipFinderServiceRole28A544E9
          - Arn
      Environment:
        Variables:
          BUCKET:
            Ref: MessageStore60E7AFC8
      Handler: handler.main
      MemorySize: 128
      Runtime: nodejs14.x
      Timeout: 900
    DependsOn:
      - ClipFinderServiceRoleDefaultPolicyAFBF3421
      - ClipFinderServiceRole28A544E9
    Metadata:
      aws:cdk:path: SlStack/ClipFinder/Resource
      aws:asset:path: /Users/russell/pillar/sl/lambdas/clipfinder
      aws:asset:property: Code
  BucketNotificationsHandler050a0587b7544547bf325f094a3db834RoleB6FB88EC:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Statement:
          - Action: sts:AssumeRole
            Effect: Allow
            Principal:
              Service: lambda.amazonaws.com
        Version: "2012-10-17"
      ManagedPolicyArns:
        - Fn::Join:
            - ""
            - - "arn:"
              - Ref: AWS::Partition
              - :iam::aws:policy/service-role/AWSLambdaBasicExecutionRole
    Metadata:
      aws:cdk:path: SlStack/BucketNotificationsHandler050a0587b7544547bf325f094a3db834/Role/Resource
  BucketNotificationsHandler050a0587b7544547bf325f094a3db834RoleDefaultPolicy2CF63D36:
    Type: AWS::IAM::Policy
    Properties:
      PolicyDocument:
        Statement:
          - Action: s3:PutBucketNotification
            Effect: Allow
            Resource: "*"
        Version: "2012-10-17"
      PolicyName: BucketNotificationsHandler050a0587b7544547bf325f094a3db834RoleDefaultPolicy2CF63D36
      Roles:
        - Ref: BucketNotificationsHandler050a0587b7544547bf325f094a3db834RoleB6FB88EC
    Metadata:
      aws:cdk:path: SlStack/BucketNotificationsHandler050a0587b7544547bf325f094a3db834/Role/DefaultPolicy/Resource
  BucketNotificationsHandler050a0587b7544547bf325f094a3db8347ECC3691:
    Type: AWS::Lambda::Function
    Properties:
      Description: AWS CloudFormation handler for "Custom::S3BucketNotifications" resources (@aws-cdk/aws-s3)
      Code:
        ZipFile: |-
          exports.handler = (event, context) => {
              // eslint-disable-next-line @typescript-eslint/no-require-imports, import/no-extraneous-dependencies
              const s3 = new (require('aws-sdk').S3)();
              // eslint-disable-next-line @typescript-eslint/no-require-imports
              const https = require('https');
              // eslint-disable-next-line @typescript-eslint/no-require-imports
              const url = require('url');
              log(JSON.stringify(event, undefined, 2));
              const props = event.ResourceProperties;
              if (event.RequestType === 'Delete') {
                  props.NotificationConfiguration = {}; // this is how you clean out notifications
              }
              const req = {
                  Bucket: props.BucketName,
                  NotificationConfiguration: props.NotificationConfiguration,
              };
              return s3.putBucketNotificationConfiguration(req, (err, data) => {
                  log({ err, data });
                  if (err) {
                      return submitResponse('FAILED', err.message + `\nMore information in CloudWatch Log Stream: ${context.logStreamName}`);
                  }
                  else {
                      return submitResponse('SUCCESS');
                  }
              });
              function log(obj) {
                  console.error(event.RequestId, event.StackId, event.LogicalResourceId, obj);
              }
              // eslint-disable-next-line max-len
              // adapted from https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-properties-lambda-function-code.html#cfn-lambda-function-code-cfnresponsemodule
              // to allow sending an error message as a reason.
              function submitResponse(responseStatus, reason) {
                  const responseBody = JSON.stringify({
                      Status: responseStatus,
                      Reason: reason || 'See the details in CloudWatch Log Stream: ' + context.logStreamName,
                      PhysicalResourceId: event.PhysicalResourceId || event.LogicalResourceId,
                      StackId: event.StackId,
                      RequestId: event.RequestId,
                      LogicalResourceId: event.LogicalResourceId,
                      NoEcho: false,
                  });
                  log({ responseBody });
                  const parsedUrl = url.parse(event.ResponseURL);
                  const options = {
                      hostname: parsedUrl.hostname,
                      port: 443,
                      path: parsedUrl.path,
                      method: 'PUT',
                      headers: {
                          'content-type': '',
                          'content-length': responseBody.length,
                      },
                  };
                  const request = https.request(options, (r) => {
                      log({ statusCode: r.statusCode, statusMessage: r.statusMessage });
                      context.done();
                  });
                  request.on('error', (error) => {
                      log({ sendError: error });
                      context.done();
                  });
                  request.write(responseBody);
                  request.end();
              }
          };
      Handler: index.handler
      Role:
        Fn::GetAtt:
          - BucketNotificationsHandler050a0587b7544547bf325f094a3db834RoleB6FB88EC
          - Arn
      Runtime: nodejs12.x
      Timeout: 300
    DependsOn:
      - BucketNotificationsHandler050a0587b7544547bf325f094a3db834RoleDefaultPolicy2CF63D36
      - BucketNotificationsHandler050a0587b7544547bf325f094a3db834RoleB6FB88EC
    Metadata:
      aws:cdk:path: SlStack/BucketNotificationsHandler050a0587b7544547bf325f094a3db834/Resource
  CDKMetadata:
    Type: AWS::CDK::Metadata
    Properties:
      Analytics: v2:deflate64:H4sIAAAAAAAAE1VQS04DMQw9C3uPy1B1wQ6o1HU1cIHUYyp3JkkVJyAU5e4kqYrEys/W+9ge8XmHjw8v5lsHmpdNJh8Y83s0tMDeO40hUYT9p5tYfQrE8KrKsRLO4s7wN62MownGcuTQmqqdJYp3BZp31i3mt0QLd7MbKrAae5oN5qbmYEW1KuCQHDVpY95xATEW8+TXntXr0a9CPz26owK6HUxbT7FvCeq0HpNOSkGud8t//Ye/CrVpB6UUcH5mvOjma9zh+FSfc1GRISQXxTJOt/oLL6Z5SjgBAAA=
    Metadata:
      aws:cdk:path: SlStack/CDKMetadata/Default
    Condition: CDKMetadataAvailable
Parameters:
  AssetParameters9faf4a2e9e23d7c99f598a2cee9743b3e97e406bf342999af601f2990e907147S3Bucket1545CFDC:
    Type: String
    Description: S3 bucket for asset "9faf4a2e9e23d7c99f598a2cee9743b3e97e406bf342999af601f2990e907147"
  AssetParameters9faf4a2e9e23d7c99f598a2cee9743b3e97e406bf342999af601f2990e907147S3VersionKey3025D34E:
    Type: String
    Description: S3 key for asset version "9faf4a2e9e23d7c99f598a2cee9743b3e97e406bf342999af601f2990e907147"
  AssetParameters9faf4a2e9e23d7c99f598a2cee9743b3e97e406bf342999af601f2990e907147ArtifactHashFF6EE0B5:
    Type: String
    Description: Artifact hash for asset "9faf4a2e9e23d7c99f598a2cee9743b3e97e406bf342999af601f2990e907147"
  AssetParametersb9ba1297b6c0c5415a0c53d8a98dc2351065c3f1f718e770a02231dba8f50543S3Bucket9FC5CCE8:
    Type: String
    Description: S3 bucket for asset "b9ba1297b6c0c5415a0c53d8a98dc2351065c3f1f718e770a02231dba8f50543"
  AssetParametersb9ba1297b6c0c5415a0c53d8a98dc2351065c3f1f718e770a02231dba8f50543S3VersionKey453DD4C9:
    Type: String
    Description: S3 key for asset version "b9ba1297b6c0c5415a0c53d8a98dc2351065c3f1f718e770a02231dba8f50543"
  AssetParametersb9ba1297b6c0c5415a0c53d8a98dc2351065c3f1f718e770a02231dba8f50543ArtifactHashA863D8EE:
    Type: String
    Description: Artifact hash for asset "b9ba1297b6c0c5415a0c53d8a98dc2351065c3f1f718e770a02231dba8f50543"
  AssetParametersc0f83392cea6f4d5da56e5a1290550b964ce9db33ac1f17f2e99cf5e0857bbbfS3Bucket9D0E886A:
    Type: String
    Description: S3 bucket for asset "c0f83392cea6f4d5da56e5a1290550b964ce9db33ac1f17f2e99cf5e0857bbbf"
  AssetParametersc0f83392cea6f4d5da56e5a1290550b964ce9db33ac1f17f2e99cf5e0857bbbfS3VersionKey5BF526C6:
    Type: String
    Description: S3 key for asset version "c0f83392cea6f4d5da56e5a1290550b964ce9db33ac1f17f2e99cf5e0857bbbf"
  AssetParametersc0f83392cea6f4d5da56e5a1290550b964ce9db33ac1f17f2e99cf5e0857bbbfArtifactHashF11C963C:
    Type: String
    Description: Artifact hash for asset "c0f83392cea6f4d5da56e5a1290550b964ce9db33ac1f17f2e99cf5e0857bbbf"
Conditions:
  CDKMetadataAvailable:
    Fn::Or:
      - Fn::Or:
          - Fn::Equals:
              - Ref: AWS::Region
              - af-south-1
          - Fn::Equals:
              - Ref: AWS::Region
              - ap-east-1
          - Fn::Equals:
              - Ref: AWS::Region
              - ap-northeast-1
          - Fn::Equals:
              - Ref: AWS::Region
              - ap-northeast-2
          - Fn::Equals:
              - Ref: AWS::Region
              - ap-south-1
          - Fn::Equals:
              - Ref: AWS::Region
              - ap-southeast-1
          - Fn::Equals:
              - Ref: AWS::Region
              - ap-southeast-2
          - Fn::Equals:
              - Ref: AWS::Region
              - ca-central-1
          - Fn::Equals:
              - Ref: AWS::Region
              - cn-north-1
          - Fn::Equals:
              - Ref: AWS::Region
              - cn-northwest-1
      - Fn::Or:
          - Fn::Equals:
              - Ref: AWS::Region
              - eu-central-1
          - Fn::Equals:
              - Ref: AWS::Region
              - eu-north-1
          - Fn::Equals:
              - Ref: AWS::Region
              - eu-south-1
          - Fn::Equals:
              - Ref: AWS::Region
              - eu-west-1
          - Fn::Equals:
              - Ref: AWS::Region
              - eu-west-2
          - Fn::Equals:
              - Ref: AWS::Region
              - eu-west-3
          - Fn::Equals:
              - Ref: AWS::Region
              - me-south-1
          - Fn::Equals:
              - Ref: AWS::Region
              - sa-east-1
          - Fn::Equals:
              - Ref: AWS::Region
              - us-east-1
          - Fn::Equals:
              - Ref: AWS::Region
              - us-east-2
      - Fn::Or:
          - Fn::Equals:
              - Ref: AWS::Region
              - us-west-1
          - Fn::Equals:
              - Ref: AWS::Region
              - us-west-2

