/* eslint-disable no-console */
import { v4 as uuidv4 } from 'uuid';
import { setClipData } from './db';

const ClipsTypeEnum = Object.freeze({ ai: 'ai', ccc: 'ccc', manual: 'manual' });

const { MONGODB_FULL_URI_ARN, DB_NAME, TESTING } = process.env;

const RUN_MONGO = TESTING === 'false' || TESTING === undefined;

const hydrateClips = (clips, type, thumbnails = []) => {
  console.log({ clips });
  return clips.map((clip, i) => ({
    type,
    id: uuidv4(),
    thumbnail_url: thumbnails[i],
    ...clip,
  }));
};

const doClipsOverlap = (clip, clip2) => {
  const { startTime, endTime } = clip;
  const { startTime: startTime2, endTime: endTime2 } = clip2;

  // if the clip is completely contained within the clip2
  if (startTime >= startTime2 && endTime <= endTime2) {
    return { ...clip2, type: 'superclip' };
  }

  // if the clip2 is completely contained within the clip
  if (startTime2 >= startTime && endTime2 <= endTime) {
    return { ...clip, type: 'superclip' };
  }

  // if clip starts before clip2
  if (startTime < startTime2) {
    return {
      ...clip,
      startTime,
      endTime: endTime2,
      type: 'superclip',
      duration: endTime2 - startTime,
    };
  }

  // if clip2 starts before clip
  if (startTime2 < startTime) {
    return {
      ...clip2,
      startTime: startTime2,
      endTime,
      type: 'superclip',
      duration: endTime - startTime2,
    };
  }

  // if clip ends after clip2
  if (endTime > endTime2) {
    return {
      ...clip,
      startTime: startTime2,
      endTime,
      type: 'superclip',
      duration: endTime - startTime2,
    };
  }

  // if clip2 ends after clip
  if (endTime2 > endTime) {
    return {
      ...clip2,
      startTime,
      endTime: endTime2,
      type: 'superclip',
      duration: endTime2 - startTime,
    };
  }

  return null;
};

exports.main = async (event) => {
  console.log(event);
  const { videoId, clips } = event[0];
  const [autoGeneratedClips, manualClips] = clips;
  const [autoGeneratedThumbnails, manualGeneratedThumbnails] = event[0].thumbnails;

  const cccClips = event[1];
  const aiHydratedClips = hydrateClips(
    autoGeneratedClips,
    ClipsTypeEnum.ai,
    autoGeneratedThumbnails,
  );
  const manualHydratedClips = hydrateClips(
    manualClips,
    ClipsTypeEnum.manual,
    manualGeneratedThumbnails,
  );

  const cccHydratedClips = hydrateClips(cccClips, ClipsTypeEnum.ccc);

  const hydratedClips = [...aiHydratedClips, ...manualHydratedClips, ...cccHydratedClips];
  const superClips = [];
  hydratedClips.forEach((clip) => {
    hydratedClips.forEach((clip2) => {
      const overlap = doClipsOverlap(clip, clip2);
      if (overlap) {
        superClips.push(overlap);
      }
    });
  });
  const allClips = [...superClips, ...clips];
  const sortedClips = allClips.sort((a, b) => a.startTime - b.startTime);
  const filteredClips = sortedClips.filter((clip) => clip.endTime - clip.startTime > 5);
  const combinedClips = {
    clips: filteredClips,
    videoId,
  };
  if (RUN_MONGO) {
    const result = await setClipData(MONGODB_FULL_URI_ARN, DB_NAME, videoId, combinedClips);
    console.log(result);
  }
  return combinedClips;
};
