name: Test Lambdas

on: [push]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v2

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1

      - name: Login to ECR
        run: |
          export ecr_passwd=$(aws ecr get-login-password)
          docker login -u AWS -p $ecr_passwd https://576758376358.dkr.ecr.us-east-1.amazonaws.com

      - name: Setup Node 14
        uses: actions/setup-node@v2
        with:
          node-version: '14'

      - name: Setup Python 3.8
        uses: actions/setup-python@v2
        with:
          python-version: 3.8

      - name: Update NPM
        run: npm i -g npm@latest

      - name: Install CDK
        run: npm i -g aws-cdk

      - name: Install Dependencies
        run: npm i

      - name: Make Logs Directory
        run: mkdir logs

      - name: CDK Synth
        run: npm run synth

      - name: Poller Lambda
        run: |
          sam local invoke VodPoller741EDAA0 --env-vars env.json --no-event -l logs/poller.txt

      - name: Test Poller
        uses: pillargg/sam-ots@master
        with:
          file: ./logs/poller.txt

      - name: Clip Finder Lambda
        run: |
          sam local invoke ClipFinderA73374EE --env-vars env.json --event test_events/clipFinderEvent.json -l logs/clipfinder.txt

      - name: Test Clip Finder
        uses: pillargg/sam-ots@master
        with:
          file: ./logs/clipfinder.txt

      - name: CCC Finder Lambda
        run: |
          sam local invoke CCCFinder4C010E91 --env-vars env.json --event test_events/cccFinderEvent.json -l logs/cccfinder.txt

      - name: Test CCC Finder
        uses: pillargg/sam-ots@master
        with:
          file: ./logs/cccfinder.txt

      - name: Manual Clip Lambda
        run: |
          sam local invoke ManualClipD684F488 --env-vars env.json --event test_events/cccFinderEvent.json -l logs/manualclip.txt

      - name: Manual Clip Finder
        uses: pillargg/sam-ots@master
        with:
          file: ./logs/manualclip.txt

      - name: Downloader Lambda
        run: |
          sam local invoke ChatDownloader326B83C0 --env-vars env.json --event test_events/event.json -l logs/downloader.txt

      - name: Test Downloader
        uses: pillargg/sam-ots@master
        with:
          file: ./logs/downloader.txt

      - name: Thumbnail Generator Lambda
        run: |
          cd lambdas/thumbnailgenerator
          echo "AWS_ACCESS_KEY_ID=${{ secrets.AWS_ACCESS_KEY_ID }}" >> docker.env
          echo "AWS_SECRET_ACCESS_KEY=${{ secrets.AWS_SECRET_ACCESS_KEY }}" >> docker.env
          docker build -t thumbnail-test .
          docker run -d -p 9000:8080 --env-file docker.env thumbnail-test
          export data=$(jq '.' -c ../../test_events/thumbnailGeneratorEvent.json)
          curl -XPOST "http://localhost:9000/2015-03-31/functions/function/invocations" -d $data > ../../logs/thumbnail.json
        
      - name: Test Generator
        uses: pillargg/sam-ots@master
        with:
          file: ./logs/thumbnail.json